### ISSUE TITLE
DRV_I2C not found after Upgrade to V3.15.2

### ISSUE THREAD

**Issue by exavontim** [Microchip-MPLAB-Harmony/core#44]
I'm working on a ATSAMD20J18. After upgrading to v3.15.2, the MCC cannot load and reports that the DRV_I2C cannot be found in any of the files.
It all works perfectly fine in v3.15.1.

mcc-manifest:
``` yml
manifest_file_version: 1.0.0
project: EBD10200_SAMD20
creation_date: 2025-05-22T14:45:38.999+02:00[Europe/Berlin]
operating_system: Windows 10
mcc_mode: IDE
mcc_mode_version: v6.25
device_name: ATSAMD20J18
compiler: XC32 4.60
mcc_version: 5.5.2
mcc_core_version: 5.7.1
content_manager_version: 5.0.1
is_mcc_offline: true
is_using_prerelease_versions: false
mcc_content_registries: https://registry.npmjs.org/
device_library: {library_class: com.microchip.mcc.harmony.Harmony3Library, name: Harmony
    V3, version: 1.5.2}
packs: {name: SAMD20_DFP, version: 3.6.112}
modules:
- {name: csp, type: HARMONY, version: v3.22.3}
- {name: core, type: HARMONY, version: v3.15.1}
- {name: CMSIS_5, type: HARMONY, version: 5.9.0}
```
